### ISSUE TITLE
PIL is not supported for current python version

### ISSUE THREAD

**Issue by selimelawwa** [srli/image_steganography#1]
When trying to instal PIL, I had the below error, is there is a possible solution please?

error:

"Collecting PIL

  Could not find a version that satisfies the requirement PIL (from versions: )
No matching distribution found for PIL"

**Comment by srli** [comment]
Hmm, there isn't really enough information here. What python version are you using? How are you installing PIL?

Have you tried installing PIL for Python 2.7 via pip?

**Comment by selimelawwa** [comment]
Thanks but I already solved the problem

**Comment by selimelawwa** [comment]
I have installed PIL for python and its working fine now but thanks anyways

**Comment by srli** [comment]
Great, I'll go ahead and close this issue then.
